from dotenv import load_dotenv
import os

load_dotenv()

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

Q_AUDIOS_TO_TRANSCRIBE = os.getenv('Q_AUDIOS_TO_TRANSCRIBE')
Q_TRANSCRIPTIONS_TO_ANALYZE = os.getenv('Q_TRANSCRIPTIONS_TO_ANALYZE')
BLOB_CONNECTION_STRING = os.getenv('BLOB_CONNECTION_STRING')

MONGODB_CONNECTION_STRING = os.getenv('MONGODB_CONNECTION_STRING')
MONGODB_DB_NAME = os.getenv('MONGODB_DB_NAME')
MONGODB_COLLECTION_NAME = os.getenv('MONGODB_COLLECTION_NAME')
GOOGLE_API_KEY=os.getenv('GOOGLE_API_KEY')
GEMINI_LLM_MODEL_NAME=os.getenv('GEMINI_LLM_MODEL_NAME')